#!/usr/bin/env php
<?php

$possibleFiles = ['vendor/autoload.php', __DIR__ . '/../../autoload.php', __DIR__ . '/../autoload.php', __DIR__ . '/vendor/autoload.php'];
$file          = null;
foreach ($possibleFiles as $possibleFile) {
    if (file_exists($possibleFile)) {
        $file = $possibleFile;

        break;
    }
}

if (null === $file) {
    throw new RuntimeException('Unable to locate autoload.php file.');
}

require_once $file;

unset($possibleFiles, $possibleFile, $file);

$app = new \Symfony\Component\Console\Application();

$app->add(new \Itwmw\Validate\Ide\Helper\IdeHelperCommand());

$app->run();